spring:
  application:
    name: porganization
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
    env:
      show-values: never
    configprops:
      show-values: never
